export type ExercisePresetKey = 'running' | 'strength' | 'yoga';

export type PathKey = 'pushUpsPath' | 'flexFlow' | 'sprintBasics' | 'cardioBlast' | 'corePower' | 'balanceFlow';

export type PathCircle = {
  id: number;
  type: string;
  title: string;
  subtitle: string;
  status: 'start' | 'review' | 'go' | 'locked';
  icon: string; // icon name, to be mapped in component
  duration?: number; // duration in seconds
  sets?: number; // number of sets (default: 1)
  restBetweenSets?: number; // rest time in seconds between sets (default: 30)
  instructions?: string; // exercise instructions
};

export type ExercisePath = {
  key: PathKey;
  label: string;
  description: string;
  icon: string; // icon name for the path
  circles: PathCircle[];
};

export type ExercisePreset = {
  label: string;
  description: string;
  paths: ExercisePath[];
};

export const EXERCISE_PRESETS: Record<ExercisePresetKey, ExercisePreset> = {
  strength: {
    label: 'Strength',
    description: 'Build muscle and power through progressive training.',
    paths: [
      {
        key: 'pushUpsPath',
        label: 'Push-Up Path',
        description: 'Master perfect push-ups through progressive training.',
        icon: 'arm-flex',
        circles: [
          {
            id: 0,
            type: 'strength',
            title: 'Incline Push-Ups',
            subtitle: 'Easier form',
            status: 'start',
            icon: 'arm-flex',
            duration: 20,
            sets: 2,
            restBetweenSets: 30,
            instructions: 'Do push-ups with your hands on an elevated surface.',
          },
          {
            id: 1,
            type: 'strength',
            title: 'Knee Push-Ups',
            subtitle: 'Build strength',
            status: 'go',
            icon: 'arm-flex-outline',
            duration: 30,
            sets: 3,
            restBetweenSets: 30,
            instructions: 'Perform push-ups from your knees. Focus on full range.',
          },
          {
            id: 2,
            type: 'strength',
            title: 'Standard Push-Ups',
            subtitle: 'Clean reps',
            status: 'locked',
            icon: 'human-handsup',
            duration: 30,
            sets: 3,
            restBetweenSets: 30,
            instructions: 'Do as many strict-form push-ups as possible.',
          },
          {
            id: 3,
            type: 'strength',
            title: 'Tempo Push-Ups',
            subtitle: 'Control the motion',
            status: 'locked',
            icon: 'timer-sand',
            duration: 30,
            sets: 3,
            restBetweenSets: 30,
            instructions: '3 seconds down, 1 second up. Slow and controlled.',
          },
          {
            id: 4,
            type: 'strength',
            title: 'Push-Up Challenge',
            subtitle: 'Volume check',
            status: 'locked',
            icon: 'run-fast',
            duration: 45,
            sets: 1,
            restBetweenSets: 0,
            instructions: 'Max push-ups with good form in 45s.',
          },
          {
            id: 5,
            type: 'strength',
            title: 'Push-Up Hero',
            subtitle: 'Full mastery test',
            status: 'locked',
            icon: 'star-circle',
            duration: 60,
            sets: 1,
            restBetweenSets: 0,
            instructions: '20 clean push-ups in one go. Chest to ground, tight core.',
          },
        ],
      },
      {
        key: 'corePower',
        label: 'Core Power',
        description: 'Strengthen your core with progressive ab training.',
        icon: 'human',
        circles: [
          {
            id: 0,
            type: 'strength',
            title: 'Plank Basics',
            subtitle: 'Foundation',
            status: 'start',
            icon: 'human',
            duration: 20,
            sets: 2,
            restBetweenSets: 30,
            instructions: 'Hold a plank position with proper form.',
          },
          {
            id: 1,
            type: 'strength',
            title: 'Crunches',
            subtitle: 'Basic movement',
            status: 'go',
            icon: 'human-handsup',
            duration: 30,
            sets: 3,
            restBetweenSets: 30,
            instructions: 'Perform controlled crunches with proper breathing.',
          },
          {
            id: 2,
            type: 'strength',
            title: 'Leg Raises',
            subtitle: 'Lower abs',
            status: 'locked',
            icon: 'human-child',
            duration: 30,
            sets: 3,
            restBetweenSets: 30,
            instructions: 'Lift legs straight up while keeping back flat.',
          },
          {
            id: 3,
            type: 'strength',
            title: 'Russian Twists',
            subtitle: 'Obliques',
            status: 'locked',
            icon: 'rotate-3d-variant',
            duration: 30,
            sets: 3,
            restBetweenSets: 30,
            instructions: 'Rotate torso side to side while balancing.',
          },
          {
            id: 4,
            type: 'strength',
            title: 'Mountain Climbers',
            subtitle: 'Dynamic core',
            status: 'locked',
            icon: 'run-fast',
            duration: 45,
            sets: 1,
            restBetweenSets: 0,
            instructions: 'Alternate bringing knees to chest in plank position.',
          },
          {
            id: 5,
            type: 'strength',
            title: 'Core Master',
            subtitle: 'Complete core test',
            status: 'locked',
            icon: 'star-circle',
            duration: 60,
            sets: 1,
            restBetweenSets: 0,
            instructions: 'Complete a full core circuit with all exercises.',
          },
        ],
      },
    ],
  },

  yoga: {
    label: 'Yoga',
    description: 'Increase flexibility and body control through yoga poses.',
    paths: [
      {
        key: 'flexFlow',
        label: 'Flex Flow',
        description: 'Increase flexibility and body control through yoga poses.',
        icon: 'yoga',
        circles: [
          {
            id: 0,
            type: 'yoga',
            title: 'Sun Salute',
            subtitle: 'Dynamic warm-up',
            status: 'start',
            icon: 'yoga',
            duration: 30,
            sets: 1,
            restBetweenSets: 20,
            instructions: 'Perform a full sun salutation sequence.',
          },
          {
            id: 1,
            type: 'yoga',
            title: 'Downward Dog',
            subtitle: 'Stretch hamstrings',
            status: 'go',
            icon: 'dog',
            duration: 30,
            sets: 1,
            restBetweenSets: 30,
            instructions: 'Hold Downward Dog. Push through your heels.',
          },
          {
            id: 2,
            type: 'yoga',
            title: 'Warrior Series',
            subtitle: 'Hip mobility',
            status: 'locked',
            icon: 'human',
            duration: 30,
            sets: 1,
            restBetweenSets: 30,
            instructions: 'Move through Warrior I, II, and III slowly.',
          },
          {
            id: 3,
            type: 'yoga',
            title: 'Bridge Pose',
            subtitle: 'Back bend',
            status: 'locked',
            icon: 'bridge',
            duration: 30,
            sets: 1,
            restBetweenSets: 30,
            instructions: 'Hold bridge pose with your hips lifted.',
          },
          {
            id: 4,
            type: 'yoga',
            title: 'Pigeon Pose',
            subtitle: 'Hip opener',
            status: 'locked',
            icon: 'dog-side',
            duration: 30,
            sets: 1,
            restBetweenSets: 30,
            instructions: 'Hold pigeon pose on each side for deep stretch.',
          },
          {
            id: 5,
            type: 'yoga',
            title: 'Flow Mastery',
            subtitle: 'Final mobility sequence',
            status: 'locked',
            icon: 'star-circle-outline',
            duration: 45,
            sets: 1,
            restBetweenSets: 0,
            instructions: 'Flow through all poses fluidly without pause.',
          },
        ],
      },
      {
        key: 'balanceFlow',
        label: 'Balance Flow',
        description: 'Improve balance and stability through standing poses.',
        icon: 'tree',
        circles: [
          {
            id: 0,
            type: 'yoga',
            title: 'Tree Pose',
            subtitle: 'Basic balance',
            status: 'start',
            icon: 'tree',
            duration: 30,
            sets: 1,
            restBetweenSets: 20,
            instructions: 'Stand on one leg with foot on opposite thigh.',
          },
          {
            id: 1,
            type: 'yoga',
            title: 'Eagle Pose',
            subtitle: 'Advanced balance',
            status: 'go',
            icon: 'human',
            duration: 30,
            sets: 1,
            restBetweenSets: 30,
            instructions: 'Wrap arms and legs in eagle position.',
          },
          {
            id: 2,
            type: 'yoga',
            title: 'Dancer Pose',
            subtitle: 'Back bend balance',
            status: 'locked',
            icon: 'human-handsup',
            duration: 30,
            sets: 1,
            restBetweenSets: 30,
            instructions: 'Hold one foot behind you while reaching forward.',
          },
          {
            id: 3,
            type: 'yoga',
            title: 'Half Moon',
            subtitle: 'Side balance',
            status: 'locked',
            icon: 'moon-waning-crescent',
            duration: 30,
            sets: 1,
            restBetweenSets: 30,
            instructions: 'Balance on one leg while reaching to the side.',
          },
          {
            id: 4,
            type: 'yoga',
            title: 'Crow Pose',
            subtitle: 'Arm balance',
            status: 'locked',
            icon: 'human-child',
            duration: 30,
            sets: 1,
            restBetweenSets: 30,
            instructions: 'Balance on your hands with knees on triceps.',
          },
          {
            id: 5,
            type: 'yoga',
            title: 'Balance Master',
            subtitle: 'Complete balance test',
            status: 'locked',
            icon: 'star-circle',
            duration: 45,
            sets: 1,
            restBetweenSets: 0,
            instructions: 'Flow through all balance poses seamlessly.',
          },
        ],
      },
    ],
  },

  running: {
    label: 'Running',
    description: 'Boost your speed and endurance with running training.',
    paths: [
      {
        key: 'sprintBasics',
        label: 'Sprint Basics',
        description: 'Boost your speed and endurance with sprint training.',
        icon: 'run-fast',
        circles: [
          {
            id: 0,
            type: 'run',
            title: 'Dynamic Warm-Up',
            subtitle: 'Ready to move',
            status: 'start',
            icon: 'walk',
            duration: 30,
            sets: 1,
            restBetweenSets: 0,
            instructions: 'March, skip, and stretch to prep for movement.',
          },
          {
            id: 1,
            type: 'run',
            title: 'Strides',
            subtitle: 'Speed mechanics',
            status: 'go',
            icon: 'run-fast',
            duration: 30,
            sets: 3,
            restBetweenSets: 30,
            instructions: 'Run at 70% effort with perfect form.',
          },
          {
            id: 2,
            type: 'run',
            title: 'High Knees',
            subtitle: 'Form drill',
            status: 'locked',
            icon: 'human-handsup',
            duration: 30,
            sets: 2,
            restBetweenSets: 20,
            instructions: 'Pump knees up quickly, stay tall.',
          },
          {
            id: 3,
            type: 'run',
            title: 'Hill Sprints',
            subtitle: 'Explosive power',
            status: 'locked',
            icon: 'terrain',
            duration: 20,
            sets: 4,
            restBetweenSets: 40,
            instructions: 'Sprint uphill with high intensity.',
          },
          {
            id: 4,
            type: 'run',
            title: 'Sprint Challenge',
            subtitle: 'All-out speed test',
            status: 'locked',
            icon: 'timer',
            duration: 30,
            sets: 1,
            restBetweenSets: 0,
            instructions: '30-second sprint at max effort. Stay upright.',
          },
          {
            id: 5,
            type: 'run',
            title: 'Sprint Champ',
            subtitle: 'Final performance test',
            status: 'locked',
            icon: 'star',
            duration: 45,
            sets: 1,
            restBetweenSets: 0,
            instructions: 'Combine stride + sprint into a seamless run.',
          },
        ],
      },
      {
        key: 'cardioBlast',
        label: 'Cardio Blast',
        description: 'Build endurance with interval training.',
        icon: 'run',
        circles: [
          {
            id: 0,
            type: 'run',
            title: 'Light Jog',
            subtitle: 'Easy pace',
            status: 'start',
            icon: 'walk',
            duration: 30,
            sets: 1,
            restBetweenSets: 0,
            instructions: 'Jog at a comfortable pace to warm up.',
          },
          {
            id: 1,
            type: 'run',
            title: 'Fartlek Training',
            subtitle: 'Speed play',
            status: 'go',
            icon: 'run',
            duration: 30,
            sets: 3,
            restBetweenSets: 30,
            instructions: 'Alternate between fast and slow running.',
          },
          {
            id: 2,
            type: 'run',
            title: 'Tempo Run',
            subtitle: 'Sustained effort',
            status: 'locked',
            icon: 'timer-sand',
            duration: 30,
            sets: 2,
            restBetweenSets: 20,
            instructions: 'Run at a challenging but sustainable pace.',
          },
          {
            id: 3,
            type: 'run',
            title: 'Interval Training',
            subtitle: 'High intensity',
            status: 'locked',
            icon: 'run-fast',
            duration: 20,
            sets: 4,
            restBetweenSets: 40,
            instructions: 'Alternate between sprint and recovery.',
          },
          {
            id: 4,
            type: 'run',
            title: 'Endurance Test',
            subtitle: 'Long distance',
            status: 'locked',
            icon: 'road-variant',
            duration: 45,
            sets: 1,
            restBetweenSets: 0,
            instructions: 'Maintain steady pace for extended period.',
          },
          {
            id: 5,
            type: 'run',
            title: 'Cardio Master',
            subtitle: 'Complete endurance test',
            status: 'locked',
            icon: 'star',
            duration: 60,
            sets: 1,
            restBetweenSets: 0,
            instructions: 'Complete a full cardio circuit with all elements.',
          },
        ],
      },
    ],
  },
};